TESTS WITH ERRORS 
test06_GM_8Puzzle_02 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 149, in test06_GM_8Puzzle_02
    self.assertEqual(p8.getGameState(), ((1,2,3,),(8,-1,4),(7,6,5)))
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\student_code_game_masters.py", line 161, in getGameState
    answers = bindings.list_of_bindings[0]
AttributeError: 'bool' object has no attribute 'list_of_bindings'

test08_GM_8Puzzle_04 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 195, in test08_GM_8Puzzle_04
    self.assertEqual(p8.getGameState(), ((1,2,3,),(8,-1,4),(7,6,5)))
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\student_code_game_masters.py", line 161, in getGameState
    answers = bindings.list_of_bindings[0]
AttributeError: 'bool' object has no attribute 'list_of_bindings'

test09_DFS_Hanoi_01 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 52, in runPlayXSteps
    results = self.pool.apply_async(self.playXSteps, [solver, plays]).get(timeout)
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 679, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 227, in test09_DFS_Hanoi_01
    [14, ((), (), (1, 2, 3))],
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 57, in runPlayXSteps
    raise Exception("Timed out: %s" % inspect.stack()[1][3])
Exception: Timed out: test09_DFS_Hanoi_01

test10_DFS_Hanoi_02 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 52, in runPlayXSteps
    results = self.pool.apply_async(self.playXSteps, [solver, plays]).get(timeout)
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 679, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 246, in test10_DFS_Hanoi_02
    [20, ((2,5,), (4,), (1, 3))],
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 57, in runPlayXSteps
    raise Exception("Timed out: %s" % inspect.stack()[1][3])
Exception: Timed out: test10_DFS_Hanoi_02

test11_DFS_Hanoi_03 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 68, in runSolve
    self.pool.apply_async(self.solve, [solver,]).get(timeout)
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 679, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 260, in test11_DFS_Hanoi_03
    self.runSolve(solver)
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 71, in runSolve
    raise Exception("Timed out: %s" % inspect.stack()[1][3])
Exception: Timed out: test11_DFS_Hanoi_03

test12_BFS_Hanoi_01 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 278, in test12_BFS_Hanoi_01
    [22, ((2,), (3,), (1,))],
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 52, in runPlayXSteps
    results = self.pool.apply_async(self.playXSteps, [solver, plays]).get(timeout)
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 683, in get
    raise self._value
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 27, in playXSteps
    solver.solveOneStep()
TypeError: 'bool' object is not callable

test13_BFS_Hanoi_02 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 296, in test13_BFS_Hanoi_02
    [23, ((5,), (4,), (1, 2, 3))],
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 52, in runPlayXSteps
    results = self.pool.apply_async(self.playXSteps, [solver, plays]).get(timeout)
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 683, in get
    raise self._value
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 27, in playXSteps
    solver.solveOneStep()
TypeError: 'bool' object is not callable

test14_BFS_Hanoi_03 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 314, in test14_BFS_Hanoi_03
    [23, ((1, 4, 5), (), (2, 3))],
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 52, in runPlayXSteps
    results = self.pool.apply_async(self.playXSteps, [solver, plays]).get(timeout)
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 683, in get
    raise self._value
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 27, in playXSteps
    solver.solveOneStep()
TypeError: 'bool' object is not callable

test16_DFS_8Puzzle_02 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 346, in test16_DFS_8Puzzle_02
    solver = SolverDFS(p8,((1,2,3),(4,5,6),(7,8,-1)))
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\student_code_uninformed_solvers.py", line 7, in __init__
    super().__init__(gameMaster, victoryCondition)
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\solver.py", line 20, in __init__
    self.currentState = GameState(self.gm.getGameState(), 0, None)
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\student_code_game_masters.py", line 161, in getGameState
    answers = bindings.list_of_bindings[0]
AttributeError: 'bool' object has no attribute 'list_of_bindings'

test17_DFS_8Puzzle_03 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 365, in test17_DFS_8Puzzle_03
    solver = SolverDFS(p8,((1,2,3),(4,5,6),(7,8,-1)))
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\student_code_uninformed_solvers.py", line 7, in __init__
    super().__init__(gameMaster, victoryCondition)
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\solver.py", line 20, in __init__
    self.currentState = GameState(self.gm.getGameState(), 0, None)
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\student_code_game_masters.py", line 161, in getGameState
    answers = bindings.list_of_bindings[0]
AttributeError: 'bool' object has no attribute 'list_of_bindings'

test18_BFS_8Puzzle_01 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 390, in test18_BFS_8Puzzle_01
    [21, ((6, 5, 4), (1, -1, 8), (7, 3, 2))],
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 52, in runPlayXSteps
    results = self.pool.apply_async(self.playXSteps, [solver, plays]).get(timeout)
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 683, in get
    raise self._value
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 27, in playXSteps
    solver.solveOneStep()
TypeError: 'bool' object is not callable

test19_BFS_8Puzzle_02 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 409, in test19_BFS_8Puzzle_02
    [6, ((5, 4, 8), (6, 1, 2), (7, 3, -1))],
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 52, in runPlayXSteps
    results = self.pool.apply_async(self.playXSteps, [solver, plays]).get(timeout)
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 683, in get
    raise self._value
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 27, in playXSteps
    solver.solveOneStep()
TypeError: 'bool' object is not callable

test20_BFS_8Puzzle_03 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 422, in test20_BFS_8Puzzle_03
    solver = SolverBFS(p8,((1,2,3),(4,5,6),(7,8,-1)))
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\student_code_uninformed_solvers.py", line 51, in __init__
    super().__init__(gameMaster, victoryCondition)
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\solver.py", line 20, in __init__
    self.currentState = GameState(self.gm.getGameState(), 0, None)
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\student_code_game_masters.py", line 161, in getGameState
    answers = bindings.list_of_bindings[0]
AttributeError: 'bool' object has no attribute 'list_of_bindings'

-------------------------------
TESTS FAILED  
test03_GM_Hanoi_03 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 109, in test03_GM_Hanoi_03
    self.assertEqual(th.getGameState(), ((1,3,4,5),(2,),()))
AssertionError: Tuples differ: ((3, 4, 5), (2,), (1,)) != ((1, 3, 4, 5), (2,), ())

First differing element 0:
(3, 4, 5)
(1, 3, 4, 5)

- ((3, 4, 5), (2,), (1,))
?                    --

+ ((1, 3, 4, 5), (2,), ())
?   +++


test04_GM_Hanoi_04 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 124, in test04_GM_Hanoi_04
    self.assertEqual(th.getGameState(), ((1,3,4,5),(),(2,)))
AssertionError: Tuples differ: ((3, 4, 5), (), (1, 2)) != ((1, 3, 4, 5), (), (2,))

First differing element 0:
(3, 4, 5)
(1, 3, 4, 5)

- ((3, 4, 5), (), (1, 2))
?                  ^ --

+ ((1, 3, 4, 5), (), (2,))
?   +++               ^


test07_GM_8Puzzle_03 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 167, in test07_GM_8Puzzle_03
    self.assertEqual(p8.getGameState(), ((5,4,-1),(6,1,8),(7,3,2)))
AssertionError: Tuples differ: ((-1,), (), ()) != ((5, 4, -1), (6, 1, 8), (7, 3, 2))

First differing element 0:
(-1,)
(5, 4, -1)

- ((-1,), (), ())
+ ((5, 4, -1), (6, 1, 8), (7, 3, 2))

test15_DFS_8Puzzle_01 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 333, in test15_DFS_8Puzzle_01
    [20, ((-1, 1, 4), (5, 2, 3), (6, 7, 8))],
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 55, in runPlayXSteps
    self.assertEqual(results[index], expected)
AssertionError: Tuples differ: ((-1,), (), ()) != ((5, -1, 4), (6, 1, 3), (7, 2, 8))

First differing element 0:
(-1,)
(5, -1, 4)

- ((-1,), (), ())
+ ((5, -1, 4), (6, 1, 3), (7, 2, 8))

-------------------------------
TESTS SKIPPED 
-------------------------------
